### ISSUE TITLE
Template tries to install latex packages

### ISSUE THREAD

**Issue by eliocamp** [benfmeyer/quarto-copernicus#2]
I tried to render the template file to ensure that it was working as expected and noticed that the 4th code chunk was taking a long time to render. That chuck tries to install the algorithms and algorithmicx latex packages. 

````
```{r} 
#| echo: FALSE
#| message: false
tinytex::tlmgr_install(c("algorithms", "algorithmicx"))
```
````

I believe quarto documents should not attempt to install packages in general, but certainly no a sample document. It might be better to remove that chunk (the code to install those packages is already in the text) or at least to use `eval = FALSE` to prevent running it.

**Comment by benfmeyer** [comment]
Thanks for catching that. I agree that should not happen. As you say the text already mentions how to install those packages if needed so I removed the code chunk with commit f15bf96
